// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZPIServer;

#nullable disable

namespace ZPIServer.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("ZPICommunicationModels.Models.HostDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("LastImage")
                        .HasColumnType("BLOB");

                    b.Property<int?>("LastKnownStatus")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LastKnownTemperature")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LocationAltitude")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LocationLatitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SectorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("HostDevices");
                });

            modelBuilder.Entity("ZPICommunicationModels.Models.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("ZPICommunicationModels.Models.HostDevice", b =>
                {
                    b.HasOne("ZPICommunicationModels.Models.Sector", "Sector")
                        .WithMany("HostDevices")
                        .HasForeignKey("SectorId");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("ZPICommunicationModels.Models.Sector", b =>
                {
                    b.Navigation("HostDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
